<script type="text/javascript" src="js/game/Game.js"></script>
<script type="text/javascript" src="js/game/Digit.js"></script>
<script type="text/javascript" src="js/game/DoubleDigit.js"></script>
<script type="text/javascript" src="js/game/Scoreboard.js"></script>
<script type="text/javascript" src="js/game/Turkey.js"></script>
<script type="text/javascript" src="js/game/Ham.js"></script>
<script type="text/javascript" src="js/game/Goal.js"></script>
<script type="text/javascript" src="js/game/Puck.js"></script>
<script type="text/javascript" src="js/game/SoundManager.js"></script>
